# Makefile for aDelayBuzz
# reversed from cBuzz with optimization turned on
# 
TARGET	= aDelayBuzz

INTTBL	= FALSE

# board definition
BOARD = UNO
#BOARD = MEGA

# uncomment one of these linesand check for your system:
##PORT	= COM3
#PORT	= /dev/ttyACM0
PORT	= /dev/cu.usbmodem1421

# uncomment one of these lines
MAKE_BASE = ../
include $(MAKE_BASE)/include/AVRMakefile.mak
