# Makefile for aBuzz

TARGET	= aBuzz

INTTBL	= FALSE

# uncomment one of these lines and check for your system:
BOARD   = UNO

# uncomment one of these linesand check for your system:
#PORT	= COM12
#PORT	= /dev/ttyACM0
PORT	= /dev/cu.usbmodem1421

# uncomment one of these lines
MAKE_BASE = ../

include $(MAKE_BASE)/include/AVRMakefile.mak
