# Makefile for aBuzz

TARGET	= aBuzz

# uncomment one of these lines and check for your system:
MCU   	:= atmega328p

# uncomment one of these linesand check for your system:
PORT	:= /dev/cu.usbmodem1411
BAUD	:= 115200
PGMR	:= arduino

SRCS	:= $(wildcard *.S)
OBJS	:= $(SRCS:.S=.o)

ARDUINO	:= /Applications/Arduino.app/Contents/Java/hardware
INCS	:= ../include 
CFLAGS	:= -mmcu=$(MCU) -nostartfiles -I$(INCS)
LFLAGS	:= -v -p$(MCU) -c$(PGMR) -P$(PORT) -b$(BAUD)
DUDECNF	:= $(ARDUINO)/tools/avr/etc/avrdude.conf

all:	$(TARGET).hex $(TARGET).lst

%.o:	%.S
	avr-gcc $(CFLAGS) -c $< -o $@

%.elf:	$(OBJS)
	avr-gcc $(CFLAGS) $^ -o $@

%.hex:	%.elf
	avr-objcopy -O ihex -R .eeprom $< $@

%.lst:	%.elf
	avr-objdump -d $< > $@

load:	$(TARGET).hex
	avrdude -C$(DUDECNF) $(LFLAGS) -Uflash:w:$(TARGET).hex:i

clean:
	rm *.o *.elf *.lst *.hex
